//Esp: Importa los tipos y fuentes necesarios desde Next.js y Google Fonts
//Pt: Importa os tipos e fontes necessários do Next.js e Google Fonts
//Eng: Imports required types and fonts from Next.js and Google Fonts
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

//Esp: Importa los estilos globales y los componentes Navbar y Footer
//Pt: Importa os estilos globais e os componentes Navbar e Footer
//Eng: Imports global styles and Navbar and Footer components
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

//Esp: Configura la fuente Geist Sans
//Pt: Configura a fonte Geist Sans
//Eng: Configures Geist Sans font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

//Esp: Configura la fuente Geist Mono
//Pt: Configura a fonte Geist Mono
//Eng: Configures Geist Mono font
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//Esp: Puedes modificar estos datos con tu propia información.
//Pt: Podes modificar estes dados com a tua própria informação.
//Eng: You can modify this data with your own information.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Esp: Componente principal del layout de la aplicación
//Pt: Componente principal do layout da aplicação
//Eng: Main layout component of the application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //Esp: Estructura HTML principal con Navbar, contenido y Footer
    //Pt: Estrutura HTML principal com Navbar, conteúdo e Footer
    //Eng: Main HTML structure with Navbar, content and Footer
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Navbar />
        <div className="flex-1 flex flex-col">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
